packages:
  - packages/*
  - packages/extension/webviews/*
  - site
allowBuilds:
  sqlite3: true
  esbuild: true
  better-sqlite3: false
  sharp: true
  unrs-resolver: true
  '@vscode/vsce-sign': true
  keytar: true
