import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { showcases } from "../src/content/showcases.ts";
import { siteContent } from "../src/content/site.ts";
import { highlightCode, initHighlighter } from "../src/lib/highlight.ts";

type HighlightRequest = {
  key: string;
  language: "ts" | "md" | "py";
  code: string;
};

const rootDir = fileURLToPath(new URL("..", import.meta.url));
const outputPath = resolve(rootDir, "src/generated/highlights.ts");

function collectRequests(): HighlightRequest[] {
  const requests: HighlightRequest[] = [];

  for (const tab of siteContent.motivation.tabs) {
    if (tab.code && tab.language && tab.language !== "rq") {
      requests.push({
        key: `motivation:${tab.id}`,
        language: tab.language,
        code: tab.code,
      });
    }
  }

  for (const example of siteContent.syntax.examples) {
    if (example.language !== "rq") {
      requests.push({
        key: `syntax:${example.label}`,
        language: example.language,
        code: example.code,
      });
    }
  }

  for (const showcase of showcases) {
    for (const [index, block] of showcase.blocks.entries()) {
      if ("code" in block && block.language !== "rq") {
        requests.push({
          key: `showcase:${showcase.id}:${index}`,
          language: block.language,
          code: block.code,
        });
      }
    }
  }

  return requests;
}

async function main() {
  await initHighlighter();
  const requests = collectRequests();
  const entries: Record<string, string> = {};

  for (const request of requests) {
    entries[request.key] = await highlightCode(request.code, request.language);
  }

  const source = `/* eslint-disable */
// Generated by scripts/generate-highlights.mts — do not edit by hand.

export const highlights = ${JSON.stringify(entries, null, 2)} as const;

export type HighlightKey = keyof typeof highlights;

export function getHighlight(key: HighlightKey): string {
  return highlights[key];
}
`;

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, source, "utf8");
  console.log(`Wrote ${Object.keys(entries).length} highlights to ${outputPath}`);
}

await main();
