import { mkdir, unlink, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { isCodeBlock, showcases } from "../src/content/showcases.ts";
import { syntax } from "../src/content/syntax.ts";
import type { CodeLanguage } from "../src/content/types.ts";
import { highlightCode, initHighlighter } from "../src/lib/highlight.ts";

type HighlightRequest = {
  key: string;
  language: Exclude<CodeLanguage, "rq">;
  code: string;
};

const rootDir = fileURLToPath(new URL("..", import.meta.url));
const outputPath = resolve(rootDir, "src/generated/highlights.ts");

function collectRequests(): HighlightRequest[] {
  const requests: HighlightRequest[] = [];

  for (const example of syntax.examples) {
    for (const [kind, snippet] of [
      ["rule", example.rule],
      ["practical", example.practical],
    ] as const) {
      if (snippet.language !== "rq") {
        requests.push({
          key: `syntax:${example.label}:${kind}`,
          language: snippet.language,
          code: snippet.code,
        });
      }
    }
  }

  for (const showcase of showcases) {
    for (const [index, block] of showcase.blocks.entries()) {
      if (isCodeBlock(block) && block.language !== "rq") {
        requests.push({
          key: `showcase:${showcase.id}:${index}`,
          language: block.language,
          code: block.code,
        });
      }
    }
  }

  return requests;
}

async function main() {
  await initHighlighter();
  const requests = collectRequests();
  const entries: Record<string, string> = {};

  for (const request of requests) {
    entries[request.key] = await highlightCode(request.code, request.language);
  }

  // Use Record<string, string> (not `as const`) so webpack cannot tree-shake
  // entries that are only reached via dynamic showcase:\${id}:\${index} keys.
  const source = `/* eslint-disable */
// Generated by scripts/generate-highlights.mts — do not edit by hand.

export const highlights: Record<string, string> = ${JSON.stringify(entries, null, 2)};

export type HighlightKey = string;

export function getHighlight(key: HighlightKey): string {
  const html = highlights[key];
  if (typeof html !== "string") {
    throw new Error(\`Missing highlight for key "\${key}". Run generate-highlights.\`);
  }
  return html;
}
`;

  await mkdir(dirname(outputPath), { recursive: true });
  // Stale compiled siblings shadow highlights.ts in Next resolution.
  for (const stale of ["highlights.js", "highlights.d.ts", "highlights.js.map"]) {
    try {
      await unlink(resolve(dirname(outputPath), stale));
    } catch {
      /* absent is fine */
    }
  }
  await writeFile(outputPath, source, "utf8");
  console.log(`Wrote ${Object.keys(entries).length} highlights to ${outputPath}`);
}

await main();
