/**
 * Specta-generated TS facade stays checked in and fully typed.
 * rq:["../../../reqlan rq/core_analysis/rust_port.rq".ts_interface]
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, test } from 'vitest';
import type {
    CompletionSummary,
    DeprecationImpact,
    ExportHeaderLinkDto,
    ExportRequestDto,
    ExportResultDto,
    FileReferenceMatch,
    BrokenReferenceDto,
    FileRelatedRequirements,
    GraphSlice,
    IdeaSummary,
    InteractionDescriptor,
    RequirementMatch,
    SearchRequirementsOptions
} from '../src/native/generated.js';

const generatedPath = join(dirname(fileURLToPath(import.meta.url)), '../src/native/generated.ts');

describe('specta generated native types', () => {
    test('generated.ts is present and lists the AnalysisApi DTO surface', () => {
        const source = readFileSync(generatedPath, 'utf8');
        expect(source).toContain('Generated by reqlan-analytical export-ts');
        expect(source).toContain('export type IdeaSummary');
        expect(source).toContain('export type RequirementMatch');
        expect(source).toContain('export type SearchRequirementsOptions');
        expect(source).toContain('export type FileRelatedRequirements');
        expect(source).toContain('export type GraphSlice');
        expect(source).toContain('export type CompletionSummary');
        expect(source).toContain('export type DeprecationImpact');
        expect(source).toContain('export type ExportHeaderLinkDto');
        expect(source).toContain('export type ExportRequestDto');
        expect(source).toContain('includeGraphPage');
        expect(source).toContain('urlBase');
        expect(source).toContain('headerLink');
        expect(source).toContain('export type ExportResultDto');
        expect(source).toContain('export type InteractionDescriptor');
        expect(source).toContain('export type FileReferenceMatch');
        expect(source).toContain('export type BrokenReferenceDto');
        expect(source).toContain('fileUri');
        expect(source).toContain('lineStart');
    });

    test('generated DTO names are importable as types', () => {
        type _Check = [
            IdeaSummary,
            RequirementMatch,
            SearchRequirementsOptions,
            FileReferenceMatch,
            BrokenReferenceDto,
            FileRelatedRequirements,
            GraphSlice,
            CompletionSummary,
            DeprecationImpact,
            ExportHeaderLinkDto,
            ExportRequestDto,
            ExportResultDto,
            InteractionDescriptor
        ];
        expect(true).toBe(true);
    });
});
