import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { ReqlanGeneratedModule, ReqlanGeneratedSharedModule } from './generated/module.js';
import { ReqlanDefinitionProvider } from './reqlan-definition-provider.js';
import { ReqlanDocumentHighlightProvider } from './reqlan-document-highlight-provider.js';
import { ReqlanDocumentLinkProvider } from './reqlan-document-link-provider.js';
import { createReqlanGrammarConfig } from './reqlan-grammar-config.js';
import { ReqlanNameProvider } from './reqlan-name-provider.js';
import { ReqlanLinker } from './reqlan-linker.js';
import { ReqlanScopeComputation, ReqlanScopeProvider } from './reqlan-scope.js';
import { ReqlanCompletionProvider } from './reqlan-completion-provider.js';
import { ReqlanCodeActionProvider } from './reqlan-code-action-provider.js';
import { sharedAttributeCatalog } from './reqlan-attribute-catalog.js';
import { ReqlanInlayHintProvider } from './reqlan-inlay-hint-provider.js';
import { ReqlanSemanticTokenProvider } from './reqlan-semantic-token-provider.js';
import { ReqlanTokenBuilder } from './reqlan-token-builder.js';
import { registerRqIgnoreErrorFiltering } from './reqlan-ignore-error.js';
import { ReqlanValidator, registerValidationChecks } from './reqlan-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type ReqlanAddedServices = {
    validation: {
        ReqlanValidator: ReqlanValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type ReqlanServices = LangiumServices & ReqlanAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const ReqlanModule: Module<ReqlanServices, PartialLangiumServices & ReqlanAddedServices> = {
    validation: {
        ReqlanValidator: () => new ReqlanValidator()
    },
    references: {
        Linker: services => new ReqlanLinker(services),
        NameProvider: () => new ReqlanNameProvider(),
        ScopeComputation: services => new ReqlanScopeComputation(services),
        ScopeProvider: services => new ReqlanScopeProvider(services)
    },
    parser: {
        GrammarConfig: createReqlanGrammarConfig,
        TokenBuilder: () => new ReqlanTokenBuilder()
    },
    lsp: {
        DefinitionProvider: services => new ReqlanDefinitionProvider(services),
        DocumentHighlightProvider: services => new ReqlanDocumentHighlightProvider(services),
        DocumentLinkProvider: services => new ReqlanDocumentLinkProvider(services),
        SemanticTokenProvider: services => new ReqlanSemanticTokenProvider(services),
        InlayHintProvider: services => new ReqlanInlayHintProvider(services),
        CompletionProvider: services => new ReqlanCompletionProvider(services, sharedAttributeCatalog),
        CodeActionProvider: services => new ReqlanCodeActionProvider(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createReqlanServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Reqlan: ReqlanServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        ReqlanGeneratedSharedModule
    );
    const Reqlan = inject(
        createDefaultModule({ shared }),
        ReqlanGeneratedModule,
        ReqlanModule
    );
    shared.ServiceRegistry.register(Reqlan);
    registerValidationChecks(Reqlan);
    registerRqIgnoreErrorFiltering(shared);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Reqlan };
}
