//! rq:["../../../reqlan rq/core_analysis/rust_port.rq".ts_interface]

use reqlan_analytical::type_collection;

fn generated_header() -> &'static str {
    "// Generated by reqlan-analytical export-ts. Do not edit.\n// rq:[\"../../../reqlan rq/core_analysis/rust_port.rq\".ts_interface]\n"
}

fn generated_path() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../packages/analytical/src/native/generated.ts")
}

const REQUIRED_TYPES: &[&str] = &[
    "IdeaSummary",
    "RequirementMatch",
    "SearchRequirementsOptions",
    "FileRelatedRequirements",
    "FileReferenceMatch",
    "BrokenReferenceDto",
    "GraphSlice",
    "CompletionSummary",
    "DeprecationImpact",
    "ExportHeaderLinkDto",
    "ExportRequestDto",
    "ExportResultDto",
    "InteractionDescriptor",
];

// rq:["../../../reqlan rq/core_analysis/rust_port.rq".ts_interface]
#[test]
fn committed_generated_ts_matches_specta_export() {
    let types = type_collection();
    let typescript = specta_typescript::Typescript::default().header(generated_header());
    let actual = typescript.export(&types).expect("specta export");
    let committed = std::fs::read_to_string(generated_path())
        .unwrap_or_else(|error| panic!("missing generated.ts: {error}"));
    for name in REQUIRED_TYPES {
        let export = format!("export type {name}");
        assert!(actual.contains(&export), "specta export missing {export}");
        assert!(
            committed.contains(&export),
            "generated.ts missing {export}; run `pnpm native:types`"
        );
    }
    assert!(committed.contains("fileUri"));
    assert!(committed.contains("lineStart"));
    assert!(committed.contains("includeGraphPage"));
    assert!(committed.contains("urlBase"));
    assert!(committed.contains("headerLink"));
}
