// Generated by reqlan-analytical export-ts. Do not edit.
// rq:["../../../reqlan rq/core_analysis/rust_port.rq".ts_interface]

// This file has been generated by Specta. DO NOT EDIT.

export type BrokenReferenceDto = { fileUri: string; sourceId?: string | null; sourceName?: string | null; kind: string; label: string; sourceLine?: number | null; snippet?: string | null; severity?: string; matchCount?: number | null }

/**
 * Result of a click: session-filtered local graph slice.
 * rq:["../../../reqlan rq/cli/click.rq".click_output]
 */
export type ClickResult = { sessionKey: string; centers: IdeaSummary[]; depth: number; nodes: IdeaSummary[]; edges: EdgeDto[]; suppressedCount: number }

export type CompletionSummary = { total: number; byStatus: Partial<{ [key in string]: number }>; byTag: Partial<{ [key in string]: number }>; outstanding: IdeaSummary[]; deprecated: IdeaSummary[] }

export type DeprecationImpact = { deprecated: IdeaSummary; dependents: IdeaSummary[] }

export type EdgeDto = { id: string; sourceId: string; targetId?: string | null; targetFile?: string | null; kind: string; label?: string | null }

export type ExportHeaderLinkDto = { href: string; label: string }

export type ExportRequestDto = { format: string; outputDir: string; exportName: string; workspaceRoot?: string | null; templateId?: string; scope?: string; sourceFileUri?: string | null; includeRequirementsPage?: boolean; includeGraphPage?: boolean; printEntryFileName?: string; excludeSecretFiles?: boolean; excludeIgnoredFiles?: boolean; runtimeMode?: string; clusterStrategy?: string; includeIdeaPages?: boolean; includeFilePages?: boolean; includeCodeFilePages?: boolean; includeClusterPages?: boolean; includeAttributePages?: boolean; includePrintPages?: boolean; maxGraphNodes?: number | null; urlBase?: string | null; headerLink?: ExportHeaderLinkDto | null }

export type ExportResultDto = { outputDir: string; indexFilePath: string; printFilePath: string; dataFilePath: string }

export type FileReferenceMatch = { path: string; ideas: IdeaSummary[] }

export type FileRelatedRequirements = { fileUri: string; ideasInFile: IdeaSummary[]; referencingIdeas: IdeaSummary[]; commentLinkedIdeas: IdeaSummary[]; folderReferencingIdeas: IdeaSummary[] }

export type GraphSlice = { centerId: string; depth: number; nodes: IdeaSummary[]; edges: EdgeDto[] }

export type IdeaSummary = { id: string; name: string; kind: string; fileUri: string; lineStart: number; summary: string; status?: string | null; statusKey: string; tags: string[]; tagsKeys: string[] }

export type InteractionDescriptor = { name: string; description: string; parameters: Partial<{ [key in string]: string }> }

export type RequirementMatch = { idea: IdeaSummary; score?: number | null; reasons?: string[] | null }

export type SearchRequirementsOptions = { context?: string[] }

