

from "../ontology.rq" import extension

analysis_scope {
    The analysis functionality should be consumed by the ["../cli/cli_package.rq".cli_package] and the [extension].
    Export writers live under ["./export.rq".export_pipeline] and ["./html_export.rq".html_export].
}